### ISSUE TITLE
Metallic PBR material flicker

### ISSUE THREAD

**Issue by nukeandbeans** [Henry00IS/VertexTracer#1] opened 2023-01-22 16:01 UTC
When using the Metallic PBR shader with smoothness > 0, it causes the entire scene specularity to flicker randomly.

[Video (GitHub decided my 11mb video was too big)](https://cdn.discordapp.com/attachments/495110443606474763/1066748724916785213/2023-01-22_09-54-57.mp4)

**Comment by nukeandbeans** [comment] 2023-01-22 16:24
Strange. Now the issue doesn't appear to want to happen anymore. I'll keep posted on if I can get the issue to happen again.

**Comment by nukeandbeans** [comment] 2023-01-22 16:39
This issue appears to be replicated by using a 16-bit texture as the metalness texture (overridden in the desktop settings texture inspector).

**Comment by Henry00IS** [comment] 2023-02-10 21:46
I am unable to reproduce this in Unity 2020.3.38f1. There is also no 16-bit texture format except either ARGB 16-bit (reversed) or RGB 16-bit (missing alpha). Considering just how little code I have (regular tex2d fetches) it may even be a Unity bug.

**Comment by Henry00IS** [comment] 2023-11-14 12:09
Well, it seems this issue had its own light show but decided to pack up and leave on its own accord – must be enjoying the beach somewhere in Unity's code. Closing it now because, as it turns out, the mystery was just a texture format playing hard to get. If it decides to flicker back into existence, feel free to reopen the issue! 💡🚀

> @nukeandbeans: "I think that one is ok to close. It was an obtuse thing with a texture format that wasn't necessary."

**Closed as completed by Henry00IS** 2023-11-14 12:09 UTC
